### ISSUE TITLE
ResizeObserver loop completed with undelivered notifications. (:0)

### ISSUE THREAD

**Issue by AlexeiBugai** [wontlost-ltd/vaadin-litelement-ckeditor#18]
Hello!
I always got next error, when toolbar visible:

ResizeObserver loop completed with undelivered notifications. (:0) FlowClient.js:216
    hC FlowClient.js:216
    un FlowClient.js:982
    tn FlowClient.js:763
    vn FlowClient.js:603
    aj FlowClient.js:1001
    Ab FlowClient.js:760
    h FlowClient.js:928
    onerror FlowClient.js:929

**Comment by eroself** [comment]
Is it happening in production mode?
