### ISSUE TITLE
Problems with ReadOnly mode

### ISSUE THREAD

**Issue by AlexeiBugai** [wontlost-ltd/vaadin-litelement-ckeditor#19]
Hello!
1. I think, vaadinCKEditor.getElement().hasProperty("readonly") should return true, instead of false
2.
I create vaadinCKEditor with builder.readOnly = true (or vaadinCKEditor.setReadOnly(true))
Add button to change mode
Press button, then not possible to change mode back with vaadinCKEditor.setReadOnly(false). 
vaadinCKEditor still read only.
3. Is it possible to add property to hide toolbar in read only mode, but show in edit mode for DECOUPLED or classic types?

**Comment by eroself** [comment]
The features are added in v3.0.1
