### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by ARCHERS** [wontlost-ltd/vaadin-litelement-ckeditor#21]
Hello,

I've just tried it out in my Vaadin project and looks great.

Will you be adding the automatic pagination version of CKEditor5?

**Comment by eroself** [comment]
Pagination is premium feature.
A license is needed to use. For now, it is not supported.
I am thinking to add a function to enable users set license themselves.

**Comment by ARCHERS** [comment]
Thanks for your feedback - yes it would be nice to be able to set the license in the API. Vaadin say they are not planning to add further features to their rich text editor which is disappointing.

**Comment by wontlost-owner** [comment]
Fixed from version 2.2.0
