### ISSUE TITLE
Implement General Html support

### ISSUE THREAD

**Issue by FollowSteph** [wontlost-ltd/vaadin-litelement-ckeditor#35]
Hi Ryan,

I tried to email you directly (and put a comment on the Vaadin component page) but just in case neither reach you I'm also reaching out here. I tried to implement the extra functionality and I have to admit I'm not as familiar with how to create a custom component works, or how exactly it's hooked. I understand the concepts but I get lost in the details. That being said I was wondering if you would be interested in being sponsored to build that functionality. If so please let me know and we can work out if it's possible. Thank you.

**Comment by eroself** [comment]
Implementation done

**Comment by FollowSteph** [comment]
Hi Ryan,

Thank you for the update, it's much appreciated. I will check it out next
week. Unfortunately for us the holidays also resulted in a death in the
family so I haven't really been online. That being said things should get
back to normal next week at which point I look forward to updating. If I
see anything I'll let you know. Again thank you for the update.
