### ISSUE TITLE
Edits in source view do not get captured by ckeditor.getValue() unless you go back to the editor/normal view

### ISSUE THREAD

**Issue by FollowSteph** [wontlost-ltd/vaadin-litelement-ckeditor#40]
If you click on the source button in CKEditor (to go to the source view) and then do ckeditor.getValue() it will not get any of the latest changes in CKEditor. You have to click on the Source button again to go back to the main editor view and it will then pick up the changes.

**Comment by eroself** [comment]
It is the same issue with [this](https://github.com/ckeditor/ckeditor5/issues/11008).

**Comment by eroself** [comment]
New version released [v3.2.1](https://vaadin.com/directory/component/ckeditorvaadin/3.2.1).

**Comment by FollowSteph** [comment]
It's awesome you were able to add this to the plugin. Great job :) Great plugin :)
