### ISSUE TITLE
Sometimes the CKEditor header panel goes to the top of the screen

### ISSUE THREAD

**Issue by FollowSteph** [wontlost-ltd/vaadin-litelement-ckeditor#41]
It seems to happen randomly. I encounter it mainly when I've scrolled down and in source view but that could also be because I'm mainly working in the source view right now and just haven't noticed in the edit view. I can bring the CKEditor header back by clicking on the header. 

It's pretty random, at least I can't find a discernable pattern but once it happens it will continue to happen until I reload the page. 

I attached a gif showing the behavior. I click a lot at first but eventually I scroll down also to show more details (about 10 seconds into the gif). 

![ckeditorBug](https://user-images.githubusercontent.com/19716286/213261121-06946a7f-d1a2-43c0-8e7d-6ec50261af1e.gif)

**Comment by eroself** [comment]
I've reproduced the issue at my local env. Will get it fixed in the next release. Cheers.

**Comment by eroself** [comment]
New version released [v3.2.1](https://vaadin.com/directory/component/ckeditorvaadin/3.2.1)

**Comment by FollowSteph** [comment]
Works perfectly. Nice fix :)
