### ISSUE TITLE
Is this difference in the editor on ckeditor website even possible in the plugin?

### ISSUE THREAD

**Issue by FollowSteph** [wontlost-ltd/vaadin-litelement-ckeditor#42]
I just noticed today when trying to align an image that the popup menu was different on CKEditor's website and the plugin. Is this even something related to the plugin? Is it even possible to add this functionality? It's on an image within a table. It could be outside of the scope of the plugin but I'm asking because outside of editing the source it's hard to right/left align an image in a table cell  as it always wants to go to center. Anyways just checking to see what's even possible.

Below are a couple of screenshots showing the plugin vs the editor on CKEditor's website, specifically this editor (the one with source): https://ckeditor.com/ckeditor-5/demo/html-support/

![onlineEditor](https://user-images.githubusercontent.com/19716286/215300995-aaee7176-58d3-46f4-9114-38cf070f6157.jpg)
![plugin](https://user-images.githubusercontent.com/19716286/215300998-c5948102-3474-4cdf-a47a-dffd09660958.jpg)

**Comment by FollowSteph** [comment]
Also what's weird is that the editor with source at: https://ckeditor.com/docs/ckeditor5/latest/features/source-editing.html shows a different popup menu for the image. Is this possibly something that is configurable that's just something the vaadin plugin doesn't support or is it something within CKEditor? And if it's something not yet implemented then do you think it is a smaller or bigger effort?

**Comment by eroself** [comment]
Try this code:
```
Config config = new Config();
config.setImage(new String[][]{},
       "", new String[]{"full", "alignLeft", "alignCenter", "alignRight"},
        new String[]{"imageTextAlternative", "|",
        "imageStyle:alignLeft",
        "imageStyle:full",
        "imageStyle:alignCenter",
        "imageStyle:alignRight"}, new String[]{});
```

**Comment by eroself** [comment]
For more about image style, please check [this](https://ckeditor.com/docs/ckeditor5/11.1.1/features/image.html#defining-custom-styles).

**Comment by FollowSteph** [comment]
Thank you. That helped a lot.
