### ISSUE TITLE
Would it be possible to see how you created the code on https://wontlost-demo.azurewebsites.net/ckeditor/classic

### ISSUE THREAD

**Issue by FollowSteph** [wontlost-ltd/vaadin-litelement-ckeditor#53]
Specifically I'm trying to re-create the read only version with no toolbar. I tried to set it up new Constants.Toolbar[]{} but that just ended up going with the default toolbar. I also tried the inline and styling it through addClassname(stylename) but that caused some weird styling issues (using for example border: 1px solid black;). In any case how does one go about creating the read only ckeditor you created in your demo on that page at the top that has a border but no toolbar? 

Thank you.

**Comment by eroself** [comment]
VaadinCKEditor editor = new VaadinCKEditorBuilder().with(builder -> {
    ...
    builder.readOnly = true;
    builder.hideToolbar=true;
    ...
}).createVaadinCKEditor();

**Comment by FollowSteph** [comment]
That was exactly what I was looking for. Thank you very much.

**Comment by FollowSteph** [comment]
Forgot to close
